# Generated by Django 5.0.3 on 2024-04-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=600)),
                ('card_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('card_description', models.CharField(max_length=600)),
                ('card_type', models.CharField(max_length=600)),
            ],
        ),
    ]
